//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        public int examcode { get; set; }
        public string examname { get; set; }
        public System.DateTime examdate { get; set; }
        public int maxmarks { get; set; }
        public int cutoff { get; set; }
        public System.DateTime time { get; set; }
    }
}
