//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int stId { get; set; }
        public string stname { get; set; }
        public System.DateTime examdate { get; set; }
        public string examcode { get; set; }
        public int centercode { get; set; }
    }
}
